pushtomisp:
  network:
    address_bind: "0.0.0.0"
    port: 8001
    method: POST
    ssl: false
  system:
    maxthreads: 4
  logging:
    logfile: pushtomisp.log
    loglevel: WARNING
    
assemblyline:
  host: "192.168.0.153"
  user: "admin"
  apikey: "mispexc:bKz&8AtWBEy&sAm3HW*fr9W*w2cxT3Rim*^IrJ&OTc3371CP"
     
misp:
  url:
  apikey:
  content-type: json
